# web占用的端口
server:
  port: 8888

spring:
  activemq:
    # activemq的broker的url
    broker-url: tcp://192.168.72.128:61616
    # 连接activemq的broker所需的账号和密码
    user: admin
    password: admin
  jms:
    # 目的地是queue还是topic， false（默认） = queue    true =  topic
    pub-sub-domain: false

#  自定义队列名称。这只是个常量
myqueue: boot-activemq-queue
